Updates to use marble 2.6.x
wedeploy/generator-electric pull request #47
Opened 2017-03-10 22:02 UTC by ygorcosta

2017-03-10 22:10 UTC, ygorcosta commented
I didn't update the electrict-marble-components to `@alpha.6` because of this PR https://github.com/wedeploy/generator-electric/pull/42 but you need this version to have all the things working well

2017-03-11 01:02 UTC, robframpton requested changes

2017-03-11 01:02 UTC, Robert-Frampton commented on generators/app/templates/src/layouts/guide.soy
> +		{call topbar.render data="all" /}
Hey @ygorcosta . I think we should find a way to do this without duplicating the topbar markup. Can we just use css/media queries to achieve the mobile navigation?

2017-03-11 01:02 UTC, Robert-Frampton commented on generators/app/templates/src/layouts/topbar.soy
> +{namespace topbar}
Since this isn't a full layout, we should put this file in `src/partials`

2017-03-11 01:02 UTC, Robert-Frampton commented on generators/app/templates/src/layouts/mainGuide.soy
> +{namespace mainGuide}
I think we should try to keep the generated markup as simple as possible, and at first glance having `main`, `guide`, and `mainGuide` layouts is a little confusing, any way we can get rid of this?

2017-03-11 11:04 UTC, ygorcosta commented on generators/app/templates/src/layouts/guide.soy
> +		{call topbar.render data="all" /}
I'll try =)

2017-03-11 11:04 UTC, ygorcosta commented on generators/app/templates/src/layouts/topbar.soy
> +{namespace topbar}
ok

2017-03-11 11:08 UTC, ygorcosta commented on generators/app/templates/src/layouts/mainGuide.soy
> +{namespace mainGuide}
yes, we can. I just created this `mainGuide` template to not duplicate few lines. but it's really confusing. I'll change this

2017-03-13 19:56 UTC, ygorcosta commented
@Robert-Frampton I'm closing this PR and I'm sending a new one later with all fixes

2017-03-13 19:56 UTC, closed without merging